# Generated by Django 4.0.4 on 2022-06-13 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('photographer', 'photographer'), ('normal_user', 'normal_user')], default='normal_user', max_length=60)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('dept', models.CharField(blank=True, choices=[('ISE', 'ISE'), ('CSE', 'CSE'), ('ME', 'ME')], max_length=60, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
