# Generated by Django 4.0.4 on 2022-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.IntegerField(blank=True, choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True),
        ),
    ]
