# Generated by Django 4.0.4 on 2022-06-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_profile_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=500)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('requested_on_behalf_of', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_photographers_assigned', models.BooleanField(default=False)),
                ('is_photos_uploaded', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='users.profile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='users.profile')),
            ],
        ),
    ]
