# Generated by Django 4.0.4 on 2022-06-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_is_rejected_event_rejected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=60)),
                ('event_phase_date', models.DateField()),
                ('phase_start_time', models.TimeField(default='00:00:01')),
                ('phase_end_time', models.TimeField(default='23:59:59')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
