# Generated by Django 4.0.4 on 2022-06-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_batch'),
        ('event', '0003_eventphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhotographerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_assigned_by', to='users.profile')),
                ('event_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_phase', to='event.eventphase')),
                ('photographers', models.ManyToManyField(to='users.profile')),
            ],
        ),
    ]
