# Generated by Django 4.0.4 on 2022-06-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventphotoslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphotoslink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', unique=True),
        ),
    ]
