# Generated by Django 4.0.4 on 2022-06-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventphotoslink_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphotoslink',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
