# Generated by Django 4.0.4 on 2022-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_contact_email_event_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
