# Generated by Django 4.0.4 on 2022-06-14 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_batch'),
        ('event', '0009_event_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='waiting', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_updated_by', to='users.profile'),
        ),
        migrations.AddField(
            model_name='eventphase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventphotographerassignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventphotoslink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_name', 'from_date', 'to_date')},
        ),
        migrations.AlterUniqueTogether(
            name='eventphase',
            unique_together={('event', 'phase_name', 'event_phase_date')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rejected_by',
        ),
    ]
