# Generated by Django 4.0.4 on 2022-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_created_event_status_event_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('waiting', 'waiting')], default='waiting', max_length=30),
        ),
    ]
