# Generated by Django 4.0.4 on 2022-06-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_batch'),
        ('event', '0011_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphase',
            name='photographers',
            field=models.ManyToManyField(blank=True, null=True, to='users.profile'),
        ),
        migrations.AddField(
            model_name='eventphase',
            name='photographers_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographer_assigned_by', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='EventPhotographerAssignment',
        ),
    ]
