# Generated by Django 4.0.4 on 2022-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_batch'),
        ('event', '0012_eventphase_photographers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphase',
            name='photographers',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
