# Generated by Django 4.0.4 on 2022-06-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_eventphase_photographers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_photographers_assigned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
